-- Adiciona a coluna 'origem' para sabermos de onde a venda veio (PDV, Manual, etc.)
ALTER TABLE public.vendas
ADD COLUMN IF NOT EXISTS origem TEXT DEFAULT 'PDV';

-- Cria a tabela para armazenar o histórico de cada venda
CREATE TABLE IF NOT EXISTS public.venda_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id INT NOT NULL REFERENCES public.vendas(id) ON DELETE CASCADE,
    usuario_id INT REFERENCES public.usuarios(id),
    usuario_nome TEXT,
    acao TEXT NOT NULL,
    detalhes JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cria uma função de gatilho (trigger) para registrar o histórico
CREATE OR REPLACE FUNCTION registrar_historico_venda()
RETURNS TRIGGER AS $$
DECLARE
    user_nome TEXT;
BEGIN
    -- Tenta obter o nome do usuário (se disponível)
    SELECT nome INTO user_nome FROM public.usuarios WHERE id = TG_ARGV[0]::INT;

    IF TG_OP = 'INSERT' THEN
        INSERT INTO public.venda_historico (venda_id, usuario_id, usuario_nome, acao, detalhes)
        VALUES (NEW.id, TG_ARGV[0]::INT, user_nome, 'Criação da Venda', jsonb_build_object('status', NEW.status, 'valor', NEW.valor_total));
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO public.venda_historico (venda_id, usuario_id, usuario_nome, acao, detalhes)
        VALUES (NEW.id, TG_ARGV[0]::INT, user_nome, 'Atualização da Venda', jsonb_build_object('de_status', OLD.status, 'para_status', NEW.status));
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Anexa o gatilho à tabela de vendas (exemplo com ID de usuário fixo 1, idealmente seria dinâmico)
-- NOTA: A forma de passar o ID do usuário para o trigger pode variar.
-- Por simplicidade aqui, vamos assumir que a lógica da aplicação pode passar o ID.
-- Uma abordagem mais robusta usaria RLS ou claims JWT.
-- Por enquanto, a aplicação registrará o histórico manualmente após a ação.

-- Vamos remover os triggers e deixar a aplicação controlar o log para simplificar
DROP TRIGGER IF EXISTS on_venda_insert ON public.vendas;
DROP TRIGGER IF EXISTS on_venda_update ON public.vendas;

-- A aplicação irá inserir no 'venda_historico' manualmente.